# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(616, 270)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/num2rus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 3)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 1, 0, 1, 3)
        self.comboDischarge = QtWidgets.QComboBox(self.centralwidget)
        self.comboDischarge.setObjectName("comboDischarge")
        self.comboDischarge.addItem("")
        self.comboDischarge.addItem("")
        self.comboDischarge.addItem("")
        self.comboDischarge.addItem("")
        self.comboDischarge.addItem("")
        self.comboDischarge.addItem("")
        self.gridLayout.addWidget(self.comboDischarge, 2, 2, 1, 1)
        self.comboCurrency = QtWidgets.QComboBox(self.centralwidget)
        self.comboCurrency.setObjectName("comboCurrency")
        self.comboCurrency.addItem("")
        self.comboCurrency.addItem("")
        self.comboCurrency.addItem("")
        self.comboCurrency.addItem("")
        self.gridLayout.addWidget(self.comboCurrency, 2, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Числа словами"))
        self.comboDischarge.setItemText(0, _translate("MainWindow", "0 - целые"))
        self.comboDischarge.setItemText(1, _translate("MainWindow", "1 - десятые"))
        self.comboDischarge.setItemText(2, _translate("MainWindow", "2 - сотые"))
        self.comboDischarge.setItemText(3, _translate("MainWindow", "3 - тысячные"))
        self.comboDischarge.setItemText(4, _translate("MainWindow", "4 - десятитысячные"))
        self.comboDischarge.setItemText(5, _translate("MainWindow", "5 - стотысячные"))
        self.comboCurrency.setItemText(0, _translate("MainWindow", "Просто число"))
        self.comboCurrency.setItemText(1, _translate("MainWindow", "Рубли"))
        self.comboCurrency.setItemText(2, _translate("MainWindow", "Доллары"))
        self.comboCurrency.setItemText(3, _translate("MainWindow", "Евро"))
import res_rc
